typography_spectrum: 0.49487201892770827
color:
  brandStrength: 0.5194973249454051
  lightness: 0.45924210804514587
  saturation: 0.033052961342036724
  rhythmicContrast: 0.027541112154722214
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.8490068081300706
name: Insurance Unleashed
navigation:
  - name: Insurance Institute of Canada
    url: 'http://www.ibc.ca/on/'
    type: external
  - name: Insurance Institute of Ontario
    url: 'http://www.insuranceinstitute.ca/en/institutes-and-chapters/Ontario.aspx'
    type: external
title: Protect What you Love
description: The Sleepless Nights Are Over
